[dialog]
Ok = enter
Cancel = f10; esc; ctrl-g
Up = left; up; ctrl-p
Down = right; down; ctrl-n
# Left =
# Right =
Help = f1
Suspend = ctrl-z
Refresh = ctrl-l
ScreenList = alt-prime
ScreenNext = alt-rbrace
ScreenPrev = alt-lbrace

[menu]
Help = f1
Left = left; ctrl-b
Right = right; ctrl-f
Up = up; ctrl-p
Down = down; ctrl-n
Home = home; alt-lt; ctr-a
End = end; alt-gt ctrl-e
Enter = enter
Quit = F10; esc; ctrl-g

[input]
Home = ctrl-a; alt-lt; home; a1
End = ctrl-e; alt-gt; end; c1
Left = left; alt-left; ctrl-b
Right = right; alt-right; ctrl-f
WordLeft = ctrl-left; alt-b
WordRight = ctrl-right; alt-f
Backspace = backspace; ctrl-h
Delete = delete; ctrl-d
DeleteToWordBegin = alt-backspace
DeleteToWordEnd = alt-d
# Mark =
Remove = ctrl-w
Cut = shift-delete
Store = alt-w; ctrl-insert
Paste = shift-insert
Yank = ctrl-y
DeleteToEnd = ctrl-k
HistoryPrev = alt-p
HistoryNext = alt-n
History = alt-h
Complete = alt-tab
# Clear =
# MarkLeft =
# MarkRight =
# MarkToWordBegin =
# MarkToWordEnd =
# MarkToHome =
# MarkToEnd =

[listbox]
Up = up; ctrl-p
Down = down; ctrl-n
Top = home; alt-lt; a1
Bottom = end; alt-gt; c1
PageUp = pgup; shift-{
PageDown = pgdn; shift-}
Delete = delete; d
Clear = shift-delete; shift-d
Edit = f4
Enter = enter
Search = ctrl-s; alt-s

[radio]
Up = up; ctrl-p
Down = down; ctrl-n
Top = home; alt-lt; a1
Bottom = end; alt-gt; c1
Select = space

[help]
Help = f1
Index = f2; c
Back = f3; left; h; ctrl-b
Quit = f10; esc
Up = up; k; ctrl-p
Down = down; j; ctrl-n
PageDown = f; pgdn; space; shift-}
PageUp = b; pgup; backspace; shift-{
HalfPageDown = d
HalfPageUp = u
Top = home; ctrl-home; ctrl-pgup; a1; alt-lt; g
Bottom = end; ctrl-end; ctrl-pgdn; c1; alt-gt; shift-g
Enter = l; ctrl-f; right; enter
LinkNext = tab
LinkPrev = alt-tab
NodeNext = n
NodePrev = p

[editor]
# No remapping, just use vim instead of mcedit
