[skin]
    description = mc-4.6 skin

[lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ─
    dvert = │
    dlefttop = ┌
    drighttop = ┐
    dleftbottom = └
    drightbottom = ┘
    dtopmiddle = ┬
    dbottommiddle = ┴
    dleftmiddle = ├
    drightmiddle = ┤

[core]
    _default_ = lightgray;blue
    gauge = white;black
    input = black;cyan
    inputunchanged = black;cyan
    inputmark = cyan;black
    disabled = gray;lightgray
    reverse = black;lightgray
    inputhistory =
    shadow = gray;black
    frame = lightgray;blue

[dialog]
    _default_ = black;lightgray
    dfocus = black;cyan
    dhotnormal = blue;lightgray
    dhotfocus = blue;cyan
    dselnormal = black;cyan
    dselfocus = blue;cyan
    dtitle = blue;lightgray
    dframe = black;lightgray

[error]
    _default_ = white;red
    errdfocus = black;lightgray
    errdhotnormal = yellow;red
    errdhotfocus = yellow;lightgray
    errdtitle = yellow;red
    errdframe = white;red

[menu]
    _default_ = black;cyan
    menusel = white;black
    menuhot = yellow;cyan
    menuhotsel = yellow;black
    menuinactive = gray;cyan
    menuframe = black;cyan

[popupmenu]
    _default_ = white;cyan
    menusel = yellow;black
    menutitle = yellow;cyan
    menuframe = white;cyan

[buttonbar]
    hotkey = lightgray;black
    button = black;cyan

[statusbar]
    _default_ = black;cyan

[help]
    _default_ = black;lightgray
    helpitalic = red;lightgray
    helpbold = blue;lightgray
    helplink = black;cyan
    helpslink = yellow;blue
    helptitle = blue;lightgray
    helpframe = black;lightgray

[editor]
    _default_ = lightgray;blue
    editbold = yellow;
    editmarked = black;cyan
    editwhitespace = brightblue;blue
    editnonprintable = brown;blue
    editlinestate = white;cyan
    bookmark = white;red
    bookmarkfound = black;green
    editrightmargin = brightblue;black
#    editbg =
#    editframe =
    editframeactive = lightgray;
    editframedrag = cyan;

[widget-editor]
    window-state-char = *
    window-close-char = X
    fold-open-char = v
    fold-close-char = >
