#
# modarin256: a moderate-dark-independent 256-color skin for coole.
#
# This skin is using colors independent from the default 16 terminal colors,
# i.e., no matter how the 16 standard colors are configured, the appearance
# of coole will not be affected.
#
# There are 4 variants of this skin:
#
# modarin256
#   - default skin, no standard colors used.
#
# modarin256-defbg
#   - like modarin256, but using the default background color for core, editor,
#     menu and popupmenu backgrounds, for use with (semi-)transparent
#     background colors.
#
# modarin256root
# modarin256root-defbg
#   - like the other two skins, but for the root user, with red colors used
#     instead of green colors for things like select/focus/statusbar etc.,
#     to keep reminding the user that coole is running as root.
#
# Fallback skins for 16-color terminals (poor man's skins):
#
# modarcon16
# modarcon16-defbg
# modarcon16root
# modarcon16root-defbg
#   - like everything running in a 16-color terminal, these skins look ugly
#     and are no substitute for the 256-color versions. As some terminals don't
#     support using dark gray as background color, i used a black background
#     and adjusted the remaining colors accordingly.
#
#
# Author: Oliver Lange <modarin@bloody.in-berlin.de>
#
# Version: 1.2
#

[skin]
    description = MoDarCon16root-DefaultBG (root)
    256colors = false

[lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ─
    dvert = │
    dlefttop = ┌
    drighttop = ┐
    dleftbottom = └
    drightbottom = ┘
    dtopmiddle = ─
    dbottommiddle = ─
    dleftmiddle = ├
    drightmiddle = ┤

[core]
    _default_ = color7;default
    gauge = color15;color1
    input = color15;color0
    inputmark = color11;color1;bold
    inputunchanged = ;color0
    reverse = color0;color9
    disabled = color8;color7
    #inputhistory =
    #commandhistory =
    frame = color7;default

[dialog]
    _default_ = color0;color7
    dhotnormal = color3
    dfocus = color11;color1;bold
    dhotfocus = cyan;color1;bold
    dselnormal = color11;color1;bold
    dselfocus = white;color1;bold
    dtitle = color11;;bold
    dframe = color0;color7

[error]
    _default_ = color15;color1
    errdfocus = color11;color3;bold
    errdhotnormal = color13
    errdhotfocus = color13;color3
    errdtitle = color11;;bold
    errdframe = color15;color1

[menu]
    _default_ = color7;default
    menusel = color11;color1;bold
    menuhot = color3
    menuhotsel = cyan;color1;bold
    menuinactive = color8
    menuframe = color7;default

[popupmenu]
    _default_ = color7;default
    menusel = color11;color1;bold
    menutitle = color11;;bold
    menuframe = color7;default

[buttonbar]
    button = color7
    hotkey = color15;color3

[statusbar]
    _default_ = color15;color1

[help]
    _default_ = color0;color7
    helpitalic = color10;;bold
    helpbold = color5
    helplink = cyan
    helpslink = color11;color1;bold
    helptitle = color11;;bold
    helpframe = color0;color7

[editor]
    _default_ = color7;default
    editbold = color15;;bold
    editmarked = color11;color1;bold
    editwhitespace = color12
    editlinestate = color1;color0
    bookmark = color0;color7
    bookmarkfound = color0;color7
    editrightmargin = color0;color7

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
    fold-open-char = ▾
    fold-close-char = ▸
