name: ci-macos

on:
  workflow_call:
    inputs:
      CFLAGS:
        description: 'Custom CFLAGS'
        default: ''
        required: false
        type: string

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          brew install gettext check meson pkg-config
          brew install glib s-lang

      - name: Build default configuration
        run: |
          export CFLAGS="${{ inputs.CFLAGS }}"

          meson setup build --prefix="$(pwd)/install-prefix"
          meson compile -C build
          meson test -C build --print-errorlogs
          meson install -C build

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-logs-macos
          path: build/meson-logs/*.txt
